// 6.4 — Named constants to replace magic numbers
module.exports = {
    ANALYTICS_WINDOW_MONTHS: 6,
    MAX_SAVED_SEARCHES_PER_USER: 20,
    PLATFORM_FEE_RATE: 0.10,
    NOTIFICATION_PAGE_SIZE: 50,
    REVIEW_PAGE_SIZE: 50,
    BOOKING_MAX_DAYS: 30,
    OTP_TTL_MINUTES: 10,
    PASSWORD_RESET_TTL_MINUTES: 10,
    REFERRAL_CREDIT_AMOUNT: 50,
};
